---
title: "Slow gganimate in bookdown"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE)

remotes::install_github('rstudio/bookdown')
remotes::install_github('thomasp85/gganimate')

if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')
if (!require('dplyr')) install.packages('dplyr'); library('dplyr')
if (!require('gapminder')) install.packages('gapminder'); library('gapminder')
library('gganimate')


```


# Normal plot

```{r normal-plot1}

  ggplot(gapminder %>% filter(year == 2007), aes(gdpPercap, lifeExp, color = continent, size = country)) +
    geom_point(alpha = .3, point = 2) +
    scale_y_continuous(breaks = seq(0, 100, 5)) +
    scale_x_log10(labels = scales::dollar_format(prefix="$", suffix = "M")) +
  theme(legend.position = "none")

```


## Animated plot

```{r gganimate1}

p = ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')

# COMMENTED OUT FOR B1 and B2 tests
animate(p, renderer = ffmpeg_renderer())

```



```{r gganimate2}

# USED FOR C1 AND C2 tests
# p2 = ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
#   geom_point(alpha = 0.7, show.legend = FALSE) +
#   scale_colour_manual(values = country_colors) +
#   scale_size(range = c(2, 12)) +
#   scale_x_log10() +
#   facet_wrap(~continent) +
#   # Here comes the gganimate specific bits
#   labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
#   transition_time(year) +
#   ease_aes('linear')
# 
# animate(p2, renderer = ffmpeg_renderer())

```